Week4/address_book_folder/address_book/config/routes.rb
Rails.application.routes.draw do

get '/index' => 'contacts#index'

get '/new' => 'contacts#new' 

post '/contacts' => "contacts#create" 

get '/contacts' => 'contacts#index'

get '/contacts/show/:id' => 'contacts#show', as: :contact_show

get '/contacts/show/' => 'contacts#index'

end

Week4/address_book_folder/address_book/app/models/contact.rb
class Contact < ActiveRecord::Base
end

Week4/address_book_folder/address_book/app/models/event.rb
class Event < ActiveRecord::Base
end

Week4/address_book_folder/address_book/app/models/project.rb
class Project < ActiveRecord::Base
end

Week4/address_book_folder/address_book/app/models/user.rb
class User < ActiveRecord::Base
end

Week4/address_book_folder/address_book/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


##How this works
#validates :name, presence: true
#Contact.create(name: "John Doe").valid? # => true
#Contact.create(name: nil).valid? # => false




	def index
		@contacts = Contact.all.order(created_at: :desc).limit(10)
		#@contacts = Contact.find_by_first_letter('a').order('title ASC')
	end

	def new	
	end


	def create
	    contact = Contact.new(
	      :name => params[:contact][:name],
	      :address => params[:contact][:address],
	      :phone_number => params[:contact][:phone],
	      :email_address => params[:contact][:email])

	    	contact.save
		    redirect_to("/contacts")
	end



	def show
		@contactsdetail = Contact.find(params[:id]) 
		unless @contactsdetail
		render "no_project_found"
 		end
 	end


end

Week4/address_book_folder/address_book/app/controllers/events_controller.rb
class EventsController < ApplicationController
end

Week4/address_book_folder/address_book/app/controllers/user_controller.rb
class UserController < ApplicationController

@user = User.new(user_params)
if @user.save
	WelcomeMailer.welcome_email(@user).deliver_now
	redirect_to_user_path
else
	render :new
end

end

Week4/address_book_folder/address_book/app/helpers/contacts_helper.rb
module ContactsHelper
end

Week4/address_book_folder/address_book/app/helpers/events_helper.rb
module EventsHelper
end

Week4/address_book_folder/address_book/app/helpers/user_helper.rb
module UserHelper
end

Week4/address_book_folder/address_book/app/views/contacts/index.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="contacts.scss">
    </head>

    <body>
        <%= image_tag("logo2.png",:size => "250x100", :alt => "our logo") %>
        <!-- <div class="row">
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
        <div class="col-md-1">.col-md-1</div>
      </div> -->
      <div class="container">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <p class="bg-primary">...</p>
        	  <h1 class="text-center"><u>Habibi English</u></h1>
        	  <p class="text-center"><small>Providing quality education to the kingdom of Saudi Arabia</small></p>
        	
         </div>
          <div class="col-md-4"></div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4"></div>
        <div class="col-md-4"></div>
      </div>

      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4"></div>
        <!-- <div class="col-md-4"><h3>
      	<ol> <em>
      	<% @contacts.sort_by{ |contact| contact.name }.each do  |contact|  %>
      	
      	<li>	
      	<%= link_to contact.name, contact_show_path(contact.id) %>
      	</li>
      	<% end %>
      	 </em></ol>
      <%= link_to 'Create new post', new_path %>

      </h3>
      </div> -->
      </div>

      <br>
      <br>
      <div class="row">
        <div class="col-md-9 col-md-push-3"><p><em>
                
            'Habibi English' is a digital education platform that will use the latest 
            technology available to improve and transform educational experiences in the 
            Arab world. The main aim of the platform is to increase the access to English
            teachers for students in Arab countries, mainly females that lack access to
            quality western teachers. The benefit of using our services is that we guarantee
            culturally sensitive lessons, all teachers are trained and respect the Muslim faith.
            We have respectful teachers that will provide high quality 
            lessons for students. Also, key areas such as pronunciation, vocabulary and 
            conversational fluency can be practised and improved. The classes are live and 
            individual feedback can be provided to all students so that students can increase 
            their fluency much quicker than any other style of class. Another benefit of using
            this platform is the ability to share class costs between users  which makes it a
            cheaper than other providers and students can have classes with their friends or 
            family members. Whatever you need English for whether it be for making friends when
            travelling, improving job prospects or gaining entry to international education
            establishments - we can help you, join is today.

              </em></p>
        </div>









        <div class="col-md-3 col-md-pull-9">.</div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>

      <div class="row">
        <div class="col-sm-12">
          
          <div class="row-fluid">
            <div class="col-xs-1 col-sm-1"></div>
            <div class="col-xs-3 col-sm-3">
              <h4 class="text-left"><%= link_to "About us" %></h4>
            </div>
            <div class="col-xs-4 col-sm-4">
              <h4 class="text-center"><%= link_to "Staff members & Associates" %></h4>
            </div>
            <div class="col-xs-3 col-sm-3">
              <h4 class="text-right"><%= link_to "Sign up for classes" %></h4>
            </div>
      	
            <div class="col-xs-1 col-sm-1"></div>
          </div>
        </div>
      </div>


  </body>
</html>

Week4/address_book_folder/address_book/app/views/contacts/new.html.erb
<!-- app/views/contacts/new.html.erb -->
  

<html>
  <head>
    <title>Helpdesk sample</title>

      <script src ="jquery.js" charset="utf-8"></script>
      <script src ="app.js" charset="utf-8"></script>
  </head>

  <body>
    <%= image_tag("logo2.png",:size => "250x100", :alt => "our logo") %>

    <h1>Welcome @user</h1>
     <form action="https://plus.google.com/hangouts/_" method = "GET">
    <!-- Add the form fields for Name, Occupation, and Weapon -->
       <input type="hidden" name="gid" value="1295"/>
       <select name = "gd">
         <option>Hangouts</option>
       </select>

      <input type="submit"/>
      
    </form>
  </body>

</html>



















<!-- *This is the form to add an address input from class  
<h1>Add a new contact</h1>
<form action="/contacts" method="POST">
  <div>
    <label for="contact_name">Name</label>
    <input type="text" name="contact[name]" id="contact_name">
  </div>

  <div>
    <label for="contact_address">Address</label>
    <textarea name="contact[address]" id="contact_address"></textarea>
  </div>

  <div>
    <label for="contact_phone">Phone number</label>
    <input type="tel" name="contact[phone]" id="contact_phone">
  </div>

  <div>
    <label for="contact_email">Email</label>
    <input type="email" name="contact[email]" id="contact_email">
  </div>
  <button type="submit">Add this contact</button>
   <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
</form> -->

Week4/address_book_folder/address_book/app/views/contacts/show.html.erb
<h1><p>
The persons name is <%= @contactsdetail.name %>
</p>

<p>
The person is from <%= @contactsdetail.address %>
</p>
<p>
The person's email is <%= @contactsdetail.email_address %>
</p>

<p>
The person's number is <%= @contactsdetail.phone_number %>
</p>

</h1> 

<%= link_to 'Go to home page', index_path %>

Week4/address_book_folder/address_book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>

<body>

<%= yield %>

</body>
</html>

Week4/address_book_folder/address_book/app/views/layouts/index.html.erb
	
	  
	  <form>
	  <div>
    	<label for="contact_email">Email</label>
    	<input type="email" name="contact[email]" id="contact_email">
  	  </div>
  		<button type="submit">Add this contact</button>
   		<input type="hidden" name="authenticity_token"
      	value="<%= form_authenticity_token %>">
	</form>
	